---
repos:
  - repo: https://github.com/rhysd/actionlint.git
    rev: v1.6.8
    hooks:
      - id: actionlint-docker
        name: actionlint
        args: ["-ignore", "unexpected key \"outputs\" for \"workflow_call\" section.", "-ignore", "property \".+\" is not defined in object type"]
