name: "Test Reusable"
description: "Test Reusable Actions"

inputs:
  subject:
    description: Who to say hello to
    default: "World"
    type: string
  mybool:
    description: My boolean
    default: true
    type: boolean

outputs:
  foo:
    description: Foo
    value: ${{ steps.hello.outputs.foo }}

runs:
  using: 'composite'
  steps:
    - name: Hello
      id: hello
      shell: bash
      run: |
        echo "Hello ${{ inputs.subject }}"
        echo "My bool is ${{ inputs.mybool }}"
        if [[ "${{ inputs.mybool }}" == "true" ]]; then
          echo "yes"
        else
          echo "no"
        fi
        echo "::set-output name=foo::bar"
