name: Auto-update PRs

on:
  push:
    branches:
      - master

jobs:
  auto-update-prs:
    runs-on: ubuntu-20.04
    steps:
      - name: Auto-update PRs on merge
        uses: maxkomarychev/pr-updater-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
