---
name: "Build"

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            devops-base-image
          tags: |
            type=ref,event=branch
            type=sha,format=long,prefix=commit-
      - name: Echo
        run: echo "${{ steps.meta.outputs.tags }}"
