---
name: "Build"

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            devops-base-image
          tags: |
            type=ref,event=branch,prefix=branch-,priority=500
            type=sha,format=long,prefix=commit-,priority=200
      - name: Echo tags
        run: echo "${{ steps.meta.outputs.tags }}"
      - name: Echo JSON
        run: echo "${{ steps.meta.outputs.json }}"
      - name: Echo extracted JSON
        run: echo "${{ fromJson(steps.meta.outputs.json).tags[0] }}"
