---
name: "Build"

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            devops-base-image
          tags: |
            type=sha,format=long,prefix=commit-,priority=10000,enable=${{ github.event_name != 'pull_request' }}
            type=raw,value=${{ github.event.pull_request.head.sha }},prefix=commit-,priority=10000,enable=${{ github.event_name == 'pull_request' }}
            type=ref,event=branch,prefix=branch-,priority=9900,enable=${{ github.event_name != 'pull_request' }}
            type=raw,value=${{ github.event.pull_request.head.ref }},prefix=branch-,priority=9900,enable=${{ github.event_name == 'pull_request' }}
