name: "Check"

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master

jobs:
  is-branch-up-to-date:
    name: Is Branch Up To Date
    environment: test
    runs-on: ubuntu-20.04
    steps:
      - name: Is Branch Up To Date
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let mergingBranchSha = "${{ github.event.pull_request.base.sha }}"
            let response = await github.request("GET /repos/${{ github.event.pull_request.base.repo.full_name }}/git/ref/heads/${{ github.event.repository.default_branch }}")
            let baseBranchSha = response.data.object.sha
            if ( mergingBranchSha !== baseBranchSha ) {
              core.setFailed("Branch ${{ github.event.pull_request.head.ref }} is not up to date with ${{ github.event.repository.default_branch }}")
            }
