name: "Check"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: 
      - master
  push:
    branches-ignore: 
      - master

jobs:
  is-pr-up-to-date:
    name: Is PR Up To Date
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Is PR Up To Date
        if: github.event_name == 'pull_request'
        run: |
          base_branch="${{ github.base_ref }}"
          merging_branch="${{ github.head_ref }}"

          set +e
          git merge-base --is-ancestor "origin/$base_branch" "origin/$merging_branch"
          status=$?
          set -e

          if [[ $? -eq 1 ]]; then
            echo "::error::Branch ${merging_branch} is not up to date with ${base_branch}"
            exit 1
          elif [[ $? -ne 0 ]]; then
            echo "::error::Unable to determine if ${merging_branch} is up to date with ${base_branch}"
            exit 2
          fi
