name: "Check"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: 
      - master
  push:
    branches-ignore: 
      - master

jobs:
  is-pr-up-to-date:
    name: Is PR Up To Date
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Is PR Up To Date
        if: github.event_name == 'pull_request'
        run: |
          set -euo pipefail

          base_branch="${{ github.base_ref }}"
          merging_branch="${{ github.head_ref }}"

          git checkout origin/$base_branch
          git checkout origin/$merging_branch
          git checkout ${{ github.ref }}

          fork_point_sha=$(git merge-base --fork-point "origin/$base_branch" "origin/$merging_branch")
          echo "fork_point_sha=$fork_point_sha"
          base_branch_head_sha=$(git show-ref --hash "origin/$base_branch")
          echo "base_branch_head_sha=$base_branch_head_sha"
          
          if [[ $fork_point_sha != $base_branch_head_sha ]]; then
            echo "::error::Branch ${merging_branch} is not up to date with ${base_branch}"
            exit 1
          fi
