name: "Check"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: 
      - master
  push:
    branches-ignore: 
      - master

jobs:
  is-pr-up-to-date:
    name: Is PR Up To Date
    environment: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Is PR Up To Date
        if: github.event_name == 'pull_request'
        run: |
          set -euo pipefail

          base_branch="${{ github.base_ref }}"
          merging_branch="${{ github.head_ref }}"

          fork_point_sha=$(git merge-base --fork-point "origin/$base_branch" "origin/$merging_branch")
          base_branch_head_sha=$(git show-ref --hash "origin/$base_branch")

          echo "::error title=Yo::Branch ${merging_branch} is not up to date with ${base_branch}"
          if [[ $fork_point_sha != $base_branch_head_sha ]]; then
            echo "::error::Branch ${merging_branch} is not up to date with ${base_branch}"
          fi
