name: "Check"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: 
      - master
  push:
    branches-ignore: 
      - master

jobs:
  is-branch-up-to-date:
    name: Is Branch Up To Date
    environment: test
    runs-on: ubuntu-20.04
    steps:
      - name: Is Branch Up To Date
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if ( "${{ github.event_name }}" === "pull_request" ) {
              let mergingBranchSha = "${{ github.event.pull_request.base.sha }}"
              let branchName = "${{ github.event.pull_request.head.ref }}"
            } else {
              let mergingBranchSha = "${{ github.sha }}"
              let branchName = "${{ github.ref }}".replace("refs/heads/", "")
            }

            let response = await github.request("GET /repos/${{ github.repository }}/git/ref/heads/${{ github.event.repository.default_branch }}")
            let baseBranchSha = response.data.object.sha

            if ( mergingBranchSha !== baseBranchSha ) {
              core.setFailed(`Branch ${branchName} is not up to date with ${{ github.event.repository.default_branch }}`)
            }
