name: "Check"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: 
      - master
  push:
    branches-ignore: 
      - master

jobs:
  is-pr-up-to-date:
    name: Is PR Up To Date
    environment: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Is PR Up To Date
        if: github.event_name == 'pull_request'
        run: |
          base_ref=${{ github.base_ref }}
          merging_ref=${{ github.head_ref }}

          fork_point_sha=$(git merge-base --fork-point $base_ref $merging_ref)
          base_branch_head_sha=$(git show-ref --hash $base_ref)

          if [ $fork_point_sha != $base_branch_head_sha ]; then
            echo "::set-failed::Branch ${branchName} is not up to date with ${{ github.event.repository.default_branch }}"
          fi
