name: "Delete"

on:
  workflow_dispatch:
    inputs:
      root-page-title:
        description: "Title of top-level Confluence page to destroy under 'New Policy Development' (eg: [feature/DEVO-123-new-policy])"
        required: false
        default: ""
  delete:

jobs:
  delete:
    name: Delete
    runs-on: ubuntu-20.04
    steps:
      - run: |
          slug="${{ github.event.inputs.root-page-title }}"
          if [[ -z "$slug" ]]; then
            slug="${{ github.event.ref }}"
          slug="[$(echo "$slug" | sed -e 's/[\[\]]//g' -e 's#^refs/heads/##' | cut -c 1-50)]"
          echo SLUG=$slug
