name: "Delete"

on:
  workflow_dispatch:
    inputs:
      root-page-title:
        description: "Root Page Title (title of page tree under 'New Policy Development', eg: [feature/DEVO-123-new-policy])"
        required: false
        default: ""
  delete:

jobs:
  delete:
    name: Delete
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo $SHELL
