name: "Delete"

on:
  workflow_dispatch:
    inputs:
      root-page-title:
      required: true
      default: "${{ github.event.ref }}"
  delete:

jobs:
  delete:
    name: Delete
    runs-on: ubuntu-20.04
    steps:
      - run: |
          slug="[$(echo "${{ github.event.ref }}" | sed -e 's#^refs/heads/##' | cut -c 1-50)]"
          echo SLUG=$slug
