name: "Delete"

on:
  delete:

jobs:
  delete:
    name: Delete
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo "${{ github.ref }}"
          echo "${{ github.ref_name }}"
          echo "${{ github.event }}" | jq .
