name: "Deploy"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    name: "Deploy"
    steps:
      - name: Debug
        run: |
          echo "GITHUB_REF = '"{{ env.GITHUB_REF }}"'"
      - name: Find pull request number for branch
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.GITHUB_REF }}
      - name: Debug output
        run: |
          echo "PR number = '"{{ steps.find-pull-request.outputs.number }}"'"
      - name: Set PR Status to pending
        uses: niteoweb/pull_request_status_action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          state: pending
          description: "An example description"
          target_url: https://pansino.net
          context: deploy
          pr_number: ${{ steps.find-pull-request.outputs.number }}
          repository: ${{ env.GITHUB_REPOSITORY }}
      - name: "Checkout"
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.sha }}
