---
name: "Build"

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
