name: "Deploy"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
        GITHUB_EVENT_NAME: ${{ github.event_name == "workflow_dispatch" }}
    steps:
      - run: |
          echo "$GITHUB_EVENT_NAME"
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
