---
name: "Deploy"

on:
  pull_request:
    types:
      - closed
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  determine-image-metadata:
    if: github.event.pull_request.merged == true
    name: Determine Image Metadata
    uses: ./.github/workflows/reusable-determine-image-metadata.yml
    with:
      image: ghcr.io/opensesame/devops-base-image

  deploy:
    if: github.event.pull_request.merged == true
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1
