---
name: "Prune Docker"

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  prune-docker:
    name: Prune Docker Images
    runs-on: ubuntu-20.04
    steps:
      - uses: snok/container-retention-policy@v1
        with:
          image-names: gh-actions-test
          cut-off: two minutes ago UTC
          timestamp-to-use: updated_at
          account-type: personal
          keep-at-least: 2
          skip-tags: latest
          token: ${{ secrets.PAT }}
