name: "Test Reusable"

on:
  workflow_call:

jobs:
  test-reusable:
    name: Test Reusable
    runs-on: ubuntu-20.04
    steps:
      - name: Hello World
        run: |
          echo "Hello from a reusable workflow"
