name: "Test"

on:
  push:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
    - name: "Test Action"
      uses: tpansino/gh-actions-test/.github/actions@${{ github.sha }}
      with:
        subject: "Universe"

  test2:
    name: "Test2"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: |
          echo "foo = '${{ needs.test.outputs.foo }}'"
