name: "Test Reusable"

on:
  workflow_call:
    inputs:
      subject:
        description: Who to say hello to
        default: "World"
        type: string

jobs:
  test-reusable:
    name: Test Reusable
    runs-on: ubuntu-20.04
    outputs:
      foo: ${{ steps.hello.outputs.foo }}
    steps:
      - name: Hello
        id: hello
        run: |
          echo "Hello ${{ inputs.subject }}"
          echo "::set-output name=foo::bar"
